---
abstract: 'Generate some stuff via introspection'
author:
  - 'Dave Houston <dhouston@cpan.org>'
build_requires:
  Data::Dumper: 0
  PPI: 0
  Pod::Weaver: 0
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-Section-ClassMopper
requires:
  Class::Load: 0
  List::Util: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Pod::Elemental::Element::Nested: 0
  Pod::Elemental::Element::Pod5::Command: 0
  Pod::Elemental::Element::Pod5::Ordinary: 0
  Pod::Weaver::Role::Section: 0
version: 1.133620
